language: node_js
node_js: '10'
cache:
  directories:
    - "node_modules"
jobs:
  include:
    - stage: test
      script: commitlint-travis || travis_terminate 1
    - stage: release
      if: branch = master AND head_branch IS blank
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
